name: C++ CI

on:
  push:
    branches:
      - main

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install dependencies
      run: brew install cmake
    - name: Build and Test
      run: |
        cmake -S . -B build
        cmake --build build
        ctest --output-on-failure --test-dir build
    - name: Package
      run: |
        cmake --install build --prefix install
        cmake --build build --target package
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: lab7-macos
        path: build/*.zip

  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y cmake
    - name: Build and Test
      run: |
        cmake -S . -B build
        cmake --build build
        ctest --output-on-failure --test-dir build
    - name: Package
      run: |
        cmake --install build --prefix install
        cmake --build build --target package
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: lab7-ubuntu
        path: build/*.zip
