name: C++ CI

on:
  push:
    branches:
      - main

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake g++ python3 # Python3 нужен для сборки Boost
    - name: Fetch and Build Boost
      run: |
        mkdir -p build
        cd build
        cmake -DFETCHCONTENT_SOURCE_DIR_BOOST=${{ github.workspace }}/boost-src ..
        cmake --build . --target lab7
    - name: Test Project
      run: |
        cd build
        ctest --output-on-failure
    - name: Package
      run: |
        cd build
        cmake --install . --prefix install
        cmake --build . --target package
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: lab7-ubuntu
        path: build/*.zip
